"""Tier 3 (deterministic). Order/position state machines (3.5), broker-resident protection (R3), reconciliation (R5), square-off (A7), GTT lifecycle (A12). Never imports intelligence (R1)."""

from engine.oms.correlation import (
    DEFAULT_MAX_ENTRIES,
    BufferedUpdate,
    CorrelationAccounting,
    PendingCorrelation,
)
from engine.oms.state import (
    ALLOWED_TRANSITIONS,
    AMENDABLE_FIELDS,
    BROKER_REALITY_TRANSITIONS,
    CANCEL_REJECTED_TRANSITIONS,
    DIAGRAM_TRANSITIONS,
    MODIFICATION_CAP,
    MODIFY_REPLACE_THRESHOLD,
    TERMINAL_ORDER_STATES,
    CloseReason,
    CorrelationMismatch,
    FillQuantityError,
    IllegalTransition,
    ModificationCapExceeded,
    OrderEvent,
    OrderRole,
    OrderState,
    PlatformOrder,
    PositionState,
    ProtectionState,
    amend,
    cancel_rejected,
    correlate,
    modify_rejected,
    transition,
)
from engine.oms.store import OrderStore, StaleOrderWrite, TerminalOrderWrite
from engine.oms.updates import (
    KITE_INTERMEDIATE_STATUSES,
    KITE_STATUS_MAP,
    NOOP_FLAGS,
    BrokerUpdate,
    UnknownBrokerStatus,
    apply_update,
    parse_postback,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "AMENDABLE_FIELDS",
    "BROKER_REALITY_TRANSITIONS",
    "CANCEL_REJECTED_TRANSITIONS",
    "DEFAULT_MAX_ENTRIES",
    "DIAGRAM_TRANSITIONS",
    "KITE_INTERMEDIATE_STATUSES",
    "KITE_STATUS_MAP",
    "MODIFICATION_CAP",
    "MODIFY_REPLACE_THRESHOLD",
    "NOOP_FLAGS",
    "TERMINAL_ORDER_STATES",
    "BrokerUpdate",
    "BufferedUpdate",
    "CloseReason",
    "CorrelationAccounting",
    "CorrelationMismatch",
    "FillQuantityError",
    "IllegalTransition",
    "ModificationCapExceeded",
    "OrderEvent",
    "OrderRole",
    "OrderState",
    "OrderStore",
    "PendingCorrelation",
    "PlatformOrder",
    "PositionState",
    "ProtectionState",
    "StaleOrderWrite",
    "TerminalOrderWrite",
    "UnknownBrokerStatus",
    "amend",
    "apply_update",
    "cancel_rejected",
    "correlate",
    "modify_rejected",
    "parse_postback",
    "transition",
]
